name       : libmatekbd
version    : 1.18.0
release    : 3
source     :
    - https://pub.mate-desktop.org/releases/1.18/libmatekbd-1.18.0.tar.xz : 31bfd3891079e32b27e479a40ab8dbfbe4b44b66d6b39fe7c2b9be9aef6695e3
license    : LGPL-2.1
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --with-gtk=3.0 --disable-static
build      : |
    %make
install    : |
    %make_install
