name       : libmatekbd
version    : 1.18.2
release    : 6
source     :
    - https://pub.mate-desktop.org/releases/1.18/libmatekbd-1.18.2.tar.xz : 03df100cf931a1f6880a32b0b3eb90e82e81f6d17085bb44a2a7ca8551a00b0c
license    : LGPL-2.1
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --with-gtk=3.0 --disable-static
build      : |
    %make
install    : |
    %make_install
