name       : libmatekbd
version    : 1.20.2
release    : 10
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmatekbd-1.20.2.tar.xz : 21c3e307af2caf7fb552cfb1ea615b84acaa9f9993e7b988e3da6aa2e15d3fd0
license    : LGPL-2.1-or-later
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
