name       : libmatekbd
version    : 1.16.0
release    : 2
source     :
    - http://pub.mate-desktop.org/releases/1.16/libmatekbd-1.16.0.tar.xz : 7834c3d70892851bf5346e6b344662b5f8dc79a0f4a7cacbff5eac3bbfd26e9a
license    : LGPL-2.1
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --with-gtk=3.0 --disable-static
build      : |
    %make
install    : |
    %make_install
