name       : libmatekbd
version    : 1.26.0
release    : 19
source     :
    - https://github.com/mate-desktop/libmatekbd/releases/download/v1.26.0/libmatekbd-1.26.0.tar.xz : 220ee8cab0cbc5f42ca6b621bcd009b0b736507945a2aedbffe2235fa1d811ad
license    : LGPL-2.1-or-later
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
