name       : libmatekbd
version    : 1.20.1
release    : 8
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmatekbd-1.20.1.tar.xz : 4690737e3a572c4f31476d1536b19ef40ca0586fcbc7cfd266a170b496ed00b5
license    : LGPL-2.1-only
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
