name       : libmatekbd
version    : 1.24.0
release    : 14
source     :
    - https://github.com/mate-desktop/libmatekbd/archive/v1.24.0.tar.gz : 38427c5fcac546de2a49cbea452a7c9bf467dabfacf3e9abe501292b53217e80
license    : LGPL-2.1-or-later
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
    - mate-common
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
