name       : libmatekbd
version    : 1.20.0
release    : 7
source     :
    - https://pub.mate-desktop.org/releases/1.20/libmatekbd-1.20.0.tar.xz : 29f4bbb63b24e10a11524fde1ecca8750dbb0dd02983ec2c2951993716bc5fd8
license    : LGPL-2.1
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --with-gtk=3.0 --disable-static
build      : |
    %make
install    : |
    %make_install
