name       : libmatekbd
version    : 1.22.0
release    : 12
source     :
    - https://github.com/mate-desktop/libmatekbd/archive/v1.22.0.tar.gz : bb8e739704bac1b522af84bb2204e3779765fc87e0d6754cfbd332d2863c32a9
license    : LGPL-2.1-or-later
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
    - mate-common
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
