name       : libmatekbd
version    : 1.27.0
release    : 20
source     :
    - https://github.com/mate-desktop/libmatekbd/releases/download/v1.27.0/libmatekbd-1.27.0.tar.xz : dcebc8e76f128554da17e87597780e984f771d744aad8d7b8615106c8aecceb0
license    : LGPL-2.1-or-later
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
