name       : libmatekbd
version    : 1.24.1
release    : 18
source     :
    - https://github.com/mate-desktop/libmatekbd/archive/v1.24.1.tar.gz : e497865d5c281139a00e23bfd501dc2e77ed54fc0e4a5d53bb25bbcf601045ce
license    : LGPL-2.1-or-later
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
    - mate-common
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
