name       : libmatekbd
version    : 1.18.1
release    : 4
source     :
    - https://pub.mate-desktop.org/releases/1.18/libmatekbd-1.18.1.tar.xz : 6c1fd4686b1da3c6a25e3d358b936c3548b2c4ed424661c9b6a06f93d1b5e02f
license    : LGPL-2.1
summary    : libmatekbd is a fork of libgnomekbd
component  : desktop.mate
description: |
    libmatekbd is a fork of libgnomekbd
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
setup      : |
    %configure --with-gtk=3.0 --disable-static
build      : |
    %make
install    : |
    %make_install
